=== Mah-Cha/Projet-xml/bibliogreenit2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Bibliographie">
    <xs:complexType><!--cette balise signifie qu’il s’agit d’un élément composé d’autres éléments.-->
      <xs:sequence>
        <xs:element ref="articles_web"/>

        <xs:element ref="videos"/>
        <xs:element ref="publications"/>
        <xs:element ref="podcasts"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="articles_web"><!-- la balise "element"  reprend le nom de la balise dans le fichier xml. Ici elle est suivie de l'attribut "name", qui permet de préciser le type de donnée qui peut être saisie (ex: string, short, float …)-->
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Article" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Article">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="Auteur"/>
        <xs:element ref="Titre"/>
        <xs:element name="url" type="xs:string"/>
        <xs:element ref="parution"/>
        <xs:element name="caracteres" type="xs:string"/>
        <xs:element name="resume" type="xs:string"/>
        <xs:element ref="Illustration"/>
        <xs:element ref="mots-cles"/>
        <xs:element ref="Date_consultation"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Titre">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0">
        <xs:element name="sous-titre" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Auteur">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="prenom" type="xs:string"/>
        <xs:element name="fonction" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parution">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="jour" type="xs:string"/>
        <xs:element name="mois" type="xs:string"/>
        <xs:element name="annee" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mots-cles">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element name="tag" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Illustration">
    <xs:complexType>
      <xs:attribute name="src" type="xs:string" use="required"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="width" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Date_consultation">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="jour" type="xs:string"/>
        <xs:element name="mois" type="xs:string"/>
        <xs:element name="annee" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Video" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Video">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="Plateforme_hebergement" type="xs:string"/>
        <xs:element name="url" type="xs:string"/>
        <xs:element ref="Titre"/>
        <xs:element ref="mots-cles"/>
        <xs:element ref="parution"/>
        <xs:element ref="Auteur"/>
        <xs:element name="Nombre_de_vues" type="xs:string"/>
        <xs:element name="resume" type="xs:string"/>
        <xs:element name="Duree" type="xs:string"/>
        <xs:element ref="Illustration"/>
        <xs:element ref="Date_consultation"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="publications">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="publication" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="publication">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="Titre"/>
        <xs:element name="type_document" type="xs:string"/>
        <xs:element ref="Auteurs"/>
        <xs:element ref="concepteurs"/>
        <xs:element ref="graphisme"/>
        <xs:element name="editeur" type="xs:string"/>
        <xs:element name="pages" type="xs:string"/>
        <xs:element name="url" type="xs:string"/>
        <xs:element ref="revue"/>
        <xs:element ref="parution"/>
        <xs:element ref="Contributeurs"/>
        <xs:element ref="Revue_critique"/>
        <xs:element name="Contact" type="xs:string"/>
        <xs:element ref="Illustration"/>
        <xs:element ref="Plan"/>
        <xs:element name="resume" type="xs:string"/>
        <xs:element ref="Date_consultation"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Auteurs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="auteur" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="auteur">
    <xs:complexType mixed="true">
      <xs:choice maxOccurs="unbounded">
        <xs:element name="fonction" type="xs:string"/>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="prenom" type="xs:string"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="revue">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="numero" type="xs:string"/>
        <xs:element name="DOI" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Plan">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="chapitre" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="concepteurs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="concepteur" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="concepteur">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="prenom" type="xs:string"/>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="fonction" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="graphisme">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="prenom" type="xs:string"/>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="fonction" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Contributeurs">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contributeur" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="contributeur">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="prenom" type="xs:string"/>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="fonction" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Revue_critique">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="critique" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="critique">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="prenom" type="xs:string"/>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="fonction" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="podcasts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="podcast"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="podcast">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="url" type="xs:string"/>
        <xs:element ref="Titre"/>
        <xs:element ref="Auteurs"/>
        <xs:element name="Emission" type="xs:string"/>
        <xs:element ref="Illustration"/>
        <xs:element name="resume" type="xs:string"/>
        <xs:element ref="lien_podcast"/>
        <xs:element name="Duree" type="xs:string"/>
        <xs:element ref="Date_consultation"/>
        <xs:element ref="parution"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="lien_podcast">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="iframe"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="iframe">
    <xs:complexType>
      <xs:attribute name="frameborder" type="xs:string" use="required"/>
      <xs:attribute name="height" type="xs:string" use="required"/>
      <xs:attribute name="scrolling" type="xs:string" use="required"/>
      <xs:attribute name="src" type="xs:string" use="required"/>
      <xs:attribute name="width" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Mah-Cha/Projet-xml/bibliogreenit2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="biblio-xml-stylesheet.xsl" ?>


<Bibliographie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bibliogreenit2.xsd">
<logo src="img/logo.png"></logo>
  <articles_web>
    <Article id="art1">
      <Titre>Comment réduire l’impact des Data Centers sur l’environnement.</Titre>
      <Auteur>
        <nom>L.</nom>
        <prenom>Bastien</prenom>
        <fonction></fonction>
      </Auteur>
      <url>https://www.lebigdata.fr/data-centers-environnement</url>
      <parution>
        <jour>31</jour>
        <mois>01</mois>
        <annee>2020</annee>
      </parution>
      <caracteres>11443</caracteres>
      <resume>Les Data Centers représentent un véritable fléau pour l’environnement. Alors que la production et la consommation de données sont en passe d’exploser à l’échelle mondiale, découvrez quelles sont les pistes à explorer pour réduire la consommation d’énergie et l’impact environnemental des centres de données…</resume>
      <mots-cles>
        <tag>business</tag>
        <tag>data center</tag>
        <tag>dossiers</tag>
      </mots-cles>
      <Illustration src="img/art1.jpg" type="img/jpg"></Illustration>
      <Date_consultation>
        <jour>12</jour>
        <mois>04</mois>
        <annee>2021</annee>
      </Date_consultation>
    </Article>

    <Article id="art2">
      <url>https://www.nicomak.eu/quest-ce-que-le-green-it/</url>
      <Auteur>
        <nom>Nicomak.eu</nom><prenom></prenom><fonction></fonction>
      </Auteur>
      <Titre>Qu'est-ce que le GREEN IT?</Titre>
      <parution>
        <jour>15</jour>
        <mois>05</mois>
        <annee>2020</annee>
      </parution>
      <Illustration src="img/art2.jfif"></Illustration>
      <Date_consultation>
        <jour>25</jour>
        <mois>03</mois>
        <annee>2021</annee>
      </Date_consultation>
      <resume>Le Green IT (ou encore Informatique vert et durable) représente aujourd’hui l’ensemble des technologies de l’information et de la communication dont l’empreinte écologique et sociétale ont été volontairement réduite et qui participe à atteindre les objectifs du développement durable. Il est important de rappeler que cette démarche ne se limite pas seulement aux différents impacts sur l’environnement mais s’intéresse aussi à la performance sociale et économique de ces activités.  </resume>
      <mots-cles></mots-cles>
    </Article>


    <Article id="art3">
      <url> https://cyberjustice.blog/index.php/2021/04/01/green-it-le-numerique-responsable/</url>
      <Titre>Green it : le numérique responsable ;
        <sous-titre>Le green It et ses enjeux : Les bonnes pratiques à adopter.</sous-titre>
      </Titre>
      <Auteur>
        <nom>PEREZ</nom>
        <prenom>Emilie</prenom>
        <fonction>Master 2 Cyberjustice (promotion 2020-2021)</fonction>
      </Auteur>
      <parution>
        <jour>01</jour>
        <mois>04</mois>
        <annee>2021</annee>
      </parution>
      <Illustration src="img/art3.png"></Illustration>
      <Date_consultation>
        <jour>30</jour>
        <mois>03</mois>
        <annee>2021</annee>
      </Date_consultation>
      <resume></resume>
      <mots-cles>
        <tag>AI</tag>
        <tag>ASSISTANTS VOCAUX</tag>
        <tag>AUTHENTIFICATION PAR BIOMÉTRIE</tag>
        <tag>BIG DATA</tag>
        <tag>BREXIT</tag>
        <tag>CCPA</tag>
        <tag>CENSURE</tag>
        <tag>CHINE</tag>
        <tag>CLOUD GAMING</tag>
        <tag>CNIL</tag>
        <tag>CONSENTEMENT</tag>
        <tag>COOKIES</tag>
        <tag>CORONAVIRUS</tag>
        <tag>COVID-19</tag>
        <tag>CYBERHARCÈLEMENT</tag>
        <tag>DEEPFAKES</tag>
        <tag>DONNÉES PERSONNELLES</tag>
        <tag>DOSSIER MÉDICAL PARTAGÉ</tag>
        <tag>DROIT</tag>
        <tag>DROIT AU DÉRÉFÉRENCEMENT</tag>
        <tag>DROIT PÉNAL</tag>
        <tag>ENVIRONNEMENT</tag>
        <tag>ESPACE</tag>
        <tag>ETATS-UNIS</tag>
        <tag>EUROPE</tag>
        <tag>FAKE NEWS</tag>
        <tag>FEMME</tag>
        <tag>FRENCH TECH</tag>
        <tag>GOOGLE</tag>
        <tag>GOUVERNANCE DES DONNÉES</tag>
        <tag>GREEN BANK</tag>
        <tag>GREEN DATA CENTERS</tag>
        <tag>INTELLIGENCE ARTIFICIELLE</tag>
        <tag>JEUX VIDÉO</tag>
        <tag>NEW TECH</tag>
        <tag>OBJETS CONNECTÉS</tag>
        <tag>POLITIQUE</tag>
        <tag>POLITIQUE NUMÉRIQUE</tag>
        <tag>PRÉVENTION</tag>
        <tag>RECONNAISSANCE FACIALE</tag>
        <tag>RÉSEAUX INFORMATIQUES</tag>
        <tag>SANTÉ</tag>
        <tag>SOCIÉTÉ</tag>
        <tag>TECHNOLOGIES</tag>
        <tag>ZONE BLANCHE</tag>
      </mots-cles>
    </Article>

  </articles_web>


  <videos>
    <Video id="vid1">
      <Plateforme_hebergement>Youtube</Plateforme_hebergement>
      <url>https://www.youtube.com/watch?v=Vl16jImbHYU</url>
      <Titre>Qu'est-ce que le Green IT ou l'informatique verte?</Titre>
      <Auteur>
        <nom>DORNBUSCH</nom>
        <prenom>Philippe</prenom>
      </Auteur>
      <mots-cles>
        <tag>#numeriqueresponsable</tag>
        <tag>#greenit</tag>
        <tag>#ecologie</tag>
      </mots-cles>
      <Nombre_de_vues>1487</Nombre_de_vues>
      <parution>
        <jour>26</jour>
        <mois>10</mois>
        <annee>2019</annee>
      </parution>
      <resume>Qu'est ce que le Green It ou l'informatique verte? Quelles sont les bonnes pratiques responsables pour une sobriété numérique ?  Les réponses en clair avec notre formation  à l'IPI Institut Poly Informatique.</resume>
      <Duree>2:25</Duree>
      <Illustration src="img/vid1.jpg" width="20%"></Illustration>
      <!--<Illustration src="https://i.ytimg.com/an_webp/Vl16jImbHYU/mqdefault_6s.webp?du=3000&sqp=CJygx4QG&rs=AOn4CLAvdAzkKVvvElzQRXK1lszRriNewg"></Illustration>-->
      <Date_consultation>
        <jour>15</jour>
        <mois>04</mois>
        <annee>2021</annee>
      </Date_consultation>
    </Video>
    <Video id="vid2">
      <Plateforme_hebergement>Youtube</Plateforme_hebergement>
      <url>https://www.youtube.com/watch?v=JLEocFyAW68</url>
      <Titre>Le Numérique peut-il être vert ? | TOTEM Green IT</Titre>
      <parution>
        <jour>23</jour>
        <mois>03</mois>
        <annee>2021</annee>
      </parution>
      <Auteur>
        <nom>Bpi France</nom>
        <prenom></prenom>
        <fonction></fonction>
      </Auteur>
      <resume>Une introduction par Véronique Torner, Co-fondatrice et Présidente d'Alter Way, Administratrice Syntec Numérique, présidente du programme Numérique Responsable, en charge de l'initiative Planet Tech'Care, et Présidente Open CIO Summit (10 minutes).</resume>
      <Duree>1:02:44</Duree>
      <Nombre_de_vues>52</Nombre_de_vues>
      <Illustration src="img/vid2.jpg" width="20%"></Illustration>
      <!--<Illustration src="https://i.ytimg.com/an_webp/JLEocFyAW68/mqdefault_6s.webp?du=3000&sqp=CMLsxoQG&rs=AOn4CLAALao2n9D5cIZp_bI4K9RhOlyV1g" type="image/webp"></Illustration>-->
      <Date_consultation>
        <jour>30</jour>
        <mois>03</mois>
        <annee>2021</annee>
      </Date_consultation>
      <mots-cles><tag></tag></mots-cles>
    </Video>

    <Video id="vid3">
      <Plateforme_hebergement>Youtube</Plateforme_hebergement>
      <url>https://www.youtube.com/watch?v=iiHxCX76bYU</url>
      <Titre>L'impact des clouds sur l'environnement. ABE-RTS</Titre>
      <mots-cles>
        <tag>#numeriqueresponsable</tag>
        <tag>#greenit</tag>
        <tag>#ecologie</tag>
      </mots-cles>
      <Nombre_de_vues>45 830</Nombre_de_vues>
      <parution>
        <jour>22</jour>
        <mois>11</mois>
        <annee>2017</annee>
      </parution>
      <Auteur>
        <nom>RTS - Radio Télévision Suisse</nom>
        <prenom></prenom>
        <fonction></fonction>
      </Auteur>
      <resume>Reportage de la chaine RTS sur l’impact des clouds sur l’environnement.Alexandre Patti Gestionnaire énergie Infomaniak explique. </resume>
      <Duree>5:06</Duree>
      <!--<Illustration src="https://i.ytimg.com/an_webp/iiHxCX76bYU/mqdefault_6s.webp?du=3000&sqp=COCox4QG&rs=AOn4CLAggfQQXzvXQMS20-iU7SZrBROhEQ"></Illustration>-->
      <Date_consultation>
        <jour>30</jour>
        <mois>03</mois>
        <annee>2021</annee>
      </Date_consultation>
      <Illustration src="img/vid3.jpg" type="image/jpg" width="20%"></Illustration>
    </Video>
  </videos>

  <publications>

    <publication id="publi1">
      <url>https://journals.openedition.org/terminal/1927</url>
      <Titre>Le numérique au service de comportements durables ? Premiers pas des entreprises de « Transition Techs » </Titre>
      <Auteurs>
        <auteur><nom>PEUGEOT</nom> <prenom>Valérie</prenom><fonction></fonction></auteur>
        <auteur><nom>BEUSCART</nom><prenom>Jean-Samuel</prenom><fonction></fonction></auteur>
        <auteur><nom>PHARABOD</nom> <prenom>Anne-Sylvie</prenom><fonction></fonction></auteur>
        <auteur><nom>JOSSET</nom> <prenom>Jean-Marc</prenom><fonction></fonction></auteur>
      </Auteurs>
      <type_document>article scientifique</type_document>
      <revue>
        <nom>TERMINAL</nom>
        <numero>122/2018</numero>
        <DOI>https://doi.org/10.4000/terminal.1927</DOI>
      </revue>

      <Illustration src="img/publi1.jpeg" type="image/jpeg"></Illustration>
